### ISSUE TITLE
url is undefined, when the structure inside router-link is to complex

### ISSUE THREAD

**Issue by LasseRosenow** [hamedasemi/lit-element-router#1]
Hi I'm currently implementing your library into my lit-element web app and its pretty amazing :)
👍 👍 

But I just found some weird bug when making the structure inside a router-link element to complex:

For example I have this code:
`<router-link href="/test"><span>foo</span><span>bar</span></router-link>`

When ever I click on it, it changes the url to "undefined".

If I remove the html elements inside router-link, everything works finde.
But I really need to have some html inside there.

Thanks in advance :)

**Comment by hamedasemi** [comment]
Hi, thanks for using the router. I can see the issue, it's because the event catched by span and span does not have the href and thats why you get this error. I will fix it.

**Comment by hamedasemi** [comment]
Fixed in version 0.0.0-alpha.3

**Comment by LasseRosenow** [comment]
Thank you very much :)
👍
