### ISSUE TITLE
Pattern is not strict enough

### ISSUE THREAD

**Issue by LasseRosenow** [hamedasemi/lit-element-router#11]
I have this structure:

```
router([{
    name: 'home',
    pattern: ['', 'home']
}, {
    name: 'news',
    pattern: 'news'
}, {
    name: 'notfound',
    pattern: '*'
}], (route, params, query) => {
    this.route = route
})
```

When I go to "/news", it shows my news. That's finde.

But when I go to "/**whatever**news", it still shows my news. That should not be the case.

**Comment by hamedasemi** [comment]
Thanks for report, it is fixed now and released and published in 1.2.4
