### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by ivands** [hamedasemi/lit-element-router#16]
I'm trying to use multiple router instances but i'm getting weird errors where sometimes the first router isn't working correctly and sometimes the second one.

First off i'm getting the following error:
```
Uncaught TypeError: Cannot read property 'data' of undefined
```
At line 62 in the router-mixin.js file:
```
callback('not-found', {}, parseQuery(querystring), notFoundRoute.data);
```
It seems to me that it's an obvious bug.
Because there is no notFoundRoute route found.
The line should be:
```
callback('not-found', {}, parseQuery(querystring), {});
```

PS:
Great work btw.
Loving the router so far.

**Comment by jarrodek** [comment]
run into the same issue today. The workaround is to defined a default roiute

**Comment by hamedasemi** [comment]
Working on it and will be fixed in the next release.
