### ISSUE TITLE
Search params are added to every href

### ISSUE THREAD

**Issue by ivands** [hamedasemi/lit-element-router#23]
For some reason the search parameters are added to every navigate call.
`href + window.location.search` 

Because of this bug we can't navigate to a URL with search params inside if the page already had search params. Because you would end up with an invalid URL.
`https://test.nl?foo=bar?foo=bar`

```javascript
export let routerLinkMixin = (superclass) => class extends superclass {

    navigate(href) {
        window.history.pushState({}, null, href + window.location.search);
        window.dispatchEvent(new CustomEvent('route'));

        if (super.navigate) super.navigate();
    }
};
```

**Comment by hamedasemi** [comment]
Hi
Would you please explain more where I can reproduce and fix this issue?

**Comment by hamedasemi** [comment]
In the next release you will have this fixed.

```JavaScript
export let routerLinkMixin = (superclass) => class extends superclass {
    navigate(href) {
        window.history.pushState({}, null, href);
        window.dispatchEvent(new CustomEvent('route'));
    }
};
```
