### ISSUE TITLE
Add events for route activation

### ISSUE THREAD

**Issue by andyvanee** [hamedasemi/lit-element-router#25]
I'm curious if there is a way for a route (which extends `routerLinkMixin`) to know when it becomes active (ie: visible to the user)?

Currently, all routes are rendered at load time and then attached/detatched from the Shadow DOM. I would like to defer some data loading and rendering until the time when the route becomes visible to the user. I have come up with a solution, but I'm not sure if I'm missing something, or if something like the following should be added to the docs and possibly even added to the implementation of `routerLinkMixin`?

```js
class Page extends routerLinkMixin(LitElement) {
    // Router Links are swapped between light & shadow DOM.
    // Trigger the connected event when the parent does NOT have a shadowRoot
    connectedCallback() {
        if (!this.parentNode.shadowRoot) {
            this.dispatchEvent(new CustomEvent("connected"))
        }
        super.connectedCallback()
    }
    // Trigger the disconnected event when the parent has a shadowRoot
    disconnectedCallback() {
        if (this.parentNode.shadowRoot) {
            this.dispatchEvent(new CustomEvent("disconnected"))
        }
        super.disconnectedCallback()
    }
}
```

I'd be happy to put together a pull request if this is a feature that seems reasonable.

Thanks!

**Comment by andyvanee** [comment]
Perhaps a cleaner implementation would be to dispatch the disconnected and connected events just after the `appendChild` calls in the `routerOutlet` method?

https://github.com/hamedasemi/lit-element-router/blob/mainline/router-mixin/router-mixin.js#L98

https://github.com/hamedasemi/lit-element-router/blob/mainline/router-mixin/router-mixin.js#L102

**Comment by hamedasemi** [comment]
Hi I have planned to remove the children moving around
```JavaScript
this.appendChild(selected);
this.shadowRoot.appendChild(selected)
```
 and instead will use the JavaScript to:
```JavaScript
selected.removeAttribute('selected');
selected.setAttribute('selected');
```
and use the CSS display: none 

Simple
