### ISSUE TITLE
Optional pattern array structure

### ISSUE THREAD

**Issue by LasseRosenow** [hamedasemi/lit-element-router#3]
I think it would be great, if we could specify multiple patterns for the same route name by using a optional array structure for the pattern property:

```
router([{
    name: 'home',
    pattern: ['', 'home']
}, {
    name: 'news',
    pattern: 'news'
}, {
    name: 'notfound',
    pattern: '*'
}], (route, params, query) => {
    this.route = route
})
```

**Comment by hamedasemi** [comment]
The idea is not bad but this can be a bit confusing
```js
['home', 'dashboard'] == home || dashboard 
['home', 'dashboard'] == home/dashboard 
```

You can also alternatively do this:
```js
router([{
    name: 'home',
    pattern: ''
}, {
    name: 'home',
    pattern: 'home'
}, {
    name: 'news',
    pattern: 'news'
}, {
    name: 'notfound',
    pattern: '*'
}], (route, params, query) => {
    this.route = route
})
```

**Comment by LasseRosenow** [comment]
Well I myself wouldn't consider this as confusing, but it's your project after all. So you decide, what is best :)
I myself can life with your workaround which is what I'm doing right now anyways :D

**Comment by hamedasemi** [comment]
I will consider this in the next version design :)
