### ISSUE TITLE
Clarification regarding multi-router

### ISSUE THREAD

**Issue by tvvignesh** [hamedasemi/lit-element-router#33]
@hamedasemi Hi. I see that multi-router demo is in the works, so just had one question. Can this be used to make every component define its own routes?

For eg. 
1) `<my-org>` defines 2 routes /dashboard and /employees
2) `<org-dashboard>` and `<org-employee>` defines its own routes

so, if anyone goes to /org/dashboard/route1 the routes will be inferred from the nested components and navigation happens.

Is this possible? Any reference I can look into. I noticed all the routes defined in 1 component in the examples. Wanted to make sure that child components can have their routes and traverse like I mentioned above. Thanks.

**Comment by hamedasemi** [comment]
Hi, Thanks for using the router
The answer is yes you can make any component as an independent router regardless of other components' status.
