### ISSUE TITLE
ts typings

### ISSUE THREAD

**Issue by bennypowers** [hamedasemi/lit-element-router#7]
👋  Hi There!

I'm trying this package out for a side project. Looks nice so far.

While I'm not a TS user, my editor is ;) Please consider adding ts typings so that users can benefit from autocompletion, etc.

**Comment by hamedasemi** [comment]
Hi, thanks for using the router, certainly, it needs one, and I will create one ASAP and it will be available for the next release.

**Comment by hamedasemi** [comment]
I have implemented this and will be available in the next release.

**Comment by jrobinson01** [comment]
I'm trying to use lit-element-router in a project that uses tsc to do type checking against regular old javascript. The router works great, but tsc has two complaints:
```
node_modules/lit-element-router/lit-element-router.d.ts:12:21 - error TS2304: Cannot find name 'Observable'.

12     authenticate(): Observable<boolean> | Promise<boolean> | boolean;
                       ~~~~~~~~~~

node_modules/lit-element-router/lit-element-router.d.ts:17:18 - error TS2304: Cannot find name 'Observable'.

17     authorize(): Observable<boolean> | Promise<boolean> | boolean;
```

**Comment by hamedasemi** [comment]
I just fixed it and released a patch.

**Comment by jrobinson01** [comment]
Thanks for getting a patch out so quickly! Unfortunately, I'm not using rxjs though, so the error has changed to: 
```
node_modules/lit-element-router/lit-element-router.d.ts:13:21 - error TS2304: Cannot find name 'Observable'.

13     authenticate(): Observable<boolean> | Promise<boolean> | boolean;
```

I was able to work around it by adding `type Observable<T> = {};` to one of my files. I'm not up on typescript really (I've only used tsc with jsdoc'd js code) so not sure what effect that would have on projects that are using rxjs.

**Comment by hamedasemi** [comment]
I am not TS developer either, but I will try to find a proper way to solve this.

**Comment by jrobinson01** [comment]
Trying to understand the code there. What's the use case where the `authenticate` function returns an Observable?

**Comment by hamedasemi** [comment]
If you want to use Observables for your server communications which I don't see anyone using it up until now, maybe I can remove it until a request come to add it ;)

**Comment by hamedasemi** [comment]
I just released a new patch.
