### ISSUE TITLE
Should all slots in router-slot be rendered?

### ISSUE THREAD

**Issue by dxlbnl** [hamedasemi/lit-element-router#9]
Hi, thanks for this component!.

I've setup a couple of routes, but it looks like all pages are rendered in the dom.
![image](https://user-images.githubusercontent.com/1440704/53446666-cf680080-3a13-11e9-86ac-d64e81c82dfe.png)

**Comment by hamedasemi** [comment]
Hi, would you please send the code where I can help

**Comment by dxlbnl** [comment]
Here's my router-slot use: https://git.dxlb.nl/wolbodo/quotes/blob/master/src/lit-app.js#L73-92
But I also see this behavior in the example: https://stackblitz.com/edit/lit-element-router.

As I see it, all routes are rendered to the dom, and only made visible when the route matches. But this also triggers all onload logic of the component. 

The 'pages' are all in the shallow DOM. And the active page is in the shadowroot of the `router-slot`

**Comment by hamedasemi** [comment]
Hi I found out the problem, I will fix it ASAP. I simplified your code and it works.

```js
<router-slot route='${this.route}'>
    <page-home slot='home' .gqlClient=${this.gqlClient}></page-home>
    <page-personal slot='personal' .gqlClient=${this.gqlClient} .user=${this.user}> </page-personal>
    <page-created  slot='created' .gqlClient=${this.gqlClient} .user=${this.user}></page-created>
    <div slot='not-found'>Not Found</div>
</router-slot>
```

**Comment by hamedasemi** [comment]
Hehe :) I actually fixed another issue. I miss understood, the behaviour is exactly correct and it is the shadow dom standard behaviour which will keep all the inactive not rendered components under the parent and will put the rendered component under shadow root

**Comment by dxlbnl** [comment]
But it appears to be rendering the other components, but it doesn't display them. 
I've put some console.log statements in the render functions of the `pages`. And I see the render methods being called, when the page shouldn't show.

```
Render: home. home.js:44
Render: personal personal.js:42
Render: created created.js:42
```

**Comment by hamedasemi** [comment]
Yes you are right, it is rendering the element since you loaded the element using 
```js
import 'src/components/ui-layout'
import 'src/pages/home'
import 'src/pages/personal'
import 'src/pages/created'
import 'src/pages/create'
```
 and placed it in the page so the router does not loading or lazy loading your components in order to render them, the router does not this.

Even I got comments on this that the router should not even move the components since lit-html performance will be killed by this and they want the feature to only use css to display none them.

now What do you think? shall the router load(lazy load) the components individually on page navigation or we keep it in dom for fast load or even you vote for css display.

**Comment by dxlbnl** [comment]
I'm not sure, but I don't think I'm a fan of either suggestion.
I agree that it probably shouldn't move the components. But I don't think a CSS `display:none` trick is also sufficient. 
Since we're writing components, I don't want any of the rendering logic/methods to be called when the component is not being shown. Because I want to be able to setup event listeners, subscriptions and other stuff when the component is being added to the DOM (and as such, should be visible).

I'm not sure what the best approach will be, but I'm putting my train of thought here anyway :).
So the router-slot contains the `pages` in the shallowDOM, which (if I'm not mistaken) already triggers the rendering of the component. But maybe it does work if the router-slot can conditionally render the required slot. And thus put the slot in the shadowDOM. 

Maybe it should take all the `pages` out of the shallowDOM (in the router-slot component). And only add them when the route matches. Basically wrapping all the `pages` in a condition (if the page matches).

**Comment by dxlbnl** [comment]
Why is this closed? Is there a fix?

**Comment by jrschumacher** [comment]
@neoel I'm not sure if this is the best way, but I achieved it using:

```js
import { LitElement, html, css } from 'lit-element'
import { routerMixin } from 'lit-element-router'
import './page-one-page'
import './page-two-oage'

class App extends routerMixin(LitElement) {
  static get properties () {
    return {
      route: { type: String },
      params: { type: Object }
    }
  }

  static get routes () {
    return [
      {
        name: 'page-one',
        pattern: ''
      },
      {
        name: 'page-2',
        pattern: 'two',
        data: { component: 'page-two-page' }
      }
    ]
  }

  constructor () {
    super()
    this.route = 'main'
    this.page = this.route
    this.params = {}
  }

  onRoute (route, params, query, data) {
    let page = (data && data.component) || `${route}-page`
    if (page !== this.page) {
      this.page = html(
        [`<${page} .route=`, ` .params=`, ` .query=`, ` .data=`, ` ></${page}>`],
        route, params, query, data
      )
      this.update()
    }
  }

  render () {
    return html`${this.page}`
  }
}
```

**Comment by jrschumacher** [comment]
I made a change which allows one to pass the route params down:

```js
  onRoute (route, params, query, data) {
    let page = (data && data.component) || `${route}-page`
    if (page !== this.page) {
      this.page = html(
        [`<${page} .route=`, ` .params=`, ` .query=`, ` .data=`, ` ></${page}>`],
        route, params, query, data
      )
      this.update()
    }
  }
```
